package com.vinitech.createsynthesis.registry;

// GENERATED by tools/datagen.py, do not edit by hand.
public final class SynthesisMaterials {
	public static final String[] NAMES = {
		"fodder",
		"animal_feed",
		"fish_feed",
		"fossil_fragment",
		"stretched_hide",
		"hollow_hide",
		"horn_blank",
		"nacre",
		"soaked_hide",
		"tanned_leather",
		"saddle_frame",
		"rough_bell",
		"blank_disc",
		"polished_blank_disc",
		"clay_tablet",
		"blank_sherd",
		"ancient_soil",
		"blank_template"
	};

	private SynthesisMaterials() {
	}
}
