package com.vinitech.createsynthesis.registry;

// GENERATED by tools/datagen.py, do not edit by hand.
public final class SynthesisIncompleteItems {
	public static final String[] NAMES = {
		"growing_amethyst_cluster",
		"growing_large_amethyst_bud",
		"growing_medium_amethyst_bud",
		"growing_small_amethyst_bud",
		"incomplete_bee_nest_birch",
		"incomplete_bee_nest_oak",
		"incomplete_chainmail_boots",
		"incomplete_chainmail_chestplate",
		"incomplete_chainmail_helmet",
		"incomplete_chainmail_leggings",
		"incomplete_diamond_horse_armor",
		"incomplete_gilded_blackstone",
		"incomplete_golden_horse_armor",
		"incomplete_iron_horse_armor",
		"incomplete_rabbit_foot",
		"incomplete_sculk_sensor",
		"incomplete_scute",
		"incomplete_sniffer_egg",
		"incomplete_wet_sponge"
	};

	private SynthesisIncompleteItems() {
	}
}
